export let currentConnections = [
    {
        name: "Alex Rogers",
        email: "alex.rogers@parivedasolutions.com",
        notes: "Speak to Alex at Cox project",
        office: "Atlanta",
        frequency: "This Week",
    },
    {
        name: "Charmaine Estacio",
        email: "charmaine.estacio@parivedasolutions.com",
        notes: "Email Charmaine about React",
        office: "San Francisco",
        frequency: "Never",
    },
    {
        name: "Joel Eliason",
        email: "joel.eliason@parivedasolutions.com",
        notes: "Nothing yet",
        office: "Chicago",
        frequency: "Sometime this month",
    },
    {
        name: "Juan Vasquez",
        email: "juan.vasquez@parivedasolutions.com",
        notes: "Nothing yet",
        office: "Dallas",
        frequency: "Within 3 months",
    },  
    {
        name: "Trace Tschida",
        email: "trace@parivedasolutions.com",
        notes: "Talk to him about Angular",
        office: "Dallas",
        frequency: "This Week",
    },
    {
        name: "Stephen Godderidge",
        email: "stephen.godderidge@parivedasolutions.com",
        notes: "Nothing yet",
        office: "Philadelphia",
        frequency: "Within 6 months",
    },
    {
        name: "Jorge",
        email: "jorge@parivedasolutions.com",
        notes: "Nothing yet",
        office: "Houston",
        frequency: "Within 3 months",
    },
    {
        name: "Allison",
        email: "allison@parivedasolutions.com",
        notes: "Email Charmaine about React",
        office: "Seattle",
        frequency: "This Week",
    },
    {
        name: "Bilal",
        email: "bilal@parivedasolutions.com",
        notes: "",
        office: "Los Angeles",
        frequency: "Sometime this month",
    },
    {
        name: "Jake",
        email: "jake@parivedasolutions.com",
        notes: "",
        office: "New York",
        frequency: "Never",
    },
    {
        name: "Trevor Mason",
        email: "trevor.mason@parivedasolutions.com",
        notes: "",
        office: "Dallas",
        frequency: "Never",
    },
]